model:
  model_type: generic
  num_encoder_layers: 6
  num_encoder_heads: 8
  num_decoder_layers: 6
  num_decoder_heads: 8
  d_model: 512
  encoder_ffn_dim: 2048
  decoder_ffn_dim: 2048
  max_sequence_length: 1024

train:
  save_dir: ./results/ZZ
  num_train_epochs: 8
  learning_rate: 0.0003
  weight_decay: 0.0
  warmup_ratio: 0.0
  batch_size: 16
  test_batch_size: 16
  lr_scheduler_type: linear
  max_grad_norm: 1.0
  optimizer: adamw_torch
  num_workers: 4
  seed: 42
  wandb:
    project: calt-issac26
    group: integer_polynomial_reduction
    name: integer_polynomial_reduction
    no_wandb: False

data:
  train_dataset_path: ./data/ZZ/train_raw.txt
  test_dataset_path: ./data/ZZ/test_raw.txt
  lexer_config: ./configs/ZZ/lexer.yaml
  validate_train_tokens: true
  validate_test_tokens: true
