vocab:
  range:
    numbers: ["", 0, 1000]  # max_length=6, max_value=100 -> cumulative sum up to 600
  misc: ["+", "=", ","]
  special_tokens: {}
  flags:
    include_base_vocab: true
    include_base_special_tokens: true

number_policy:
  attach_sign: true
  digit_group: 1  # 1 digit per token
  allow_float: false

strict: true
include_base_vocab: true
