model:
  model_type: generic
  num_encoder_layers: 6
  num_encoder_heads: 8
  num_decoder_layers: 6
  num_decoder_heads: 8
  d_model: 512
  encoder_ffn_dim: 2048
  decoder_ffn_dim: 2048
  max_sequence_length: 512

train:
  save_dir: ./results/ZZ_dg1
  num_train_epochs: 64
  learning_rate: 0.0001
  weight_decay: 0.01
  warmup_ratio: 0.1
  batch_size: 128
  test_batch_size: 128
  lr_scheduler_type: linear
  max_grad_norm: 1.0
  optimizer: adamw_torch
  num_workers: 4
  seed: 42
  wandb:
    project: calt-issac26
    group: integer_addition
    name: integer_addition_dg1
    no_wandb: False

data:
  train_dataset_path: ./data/ZZ/train_raw.txt
  test_dataset_path: ./data/ZZ/test_raw.txt
  lexer_config: ./configs/ZZ_dg1/lexer.yaml
  validate_train_tokens: true
  validate_test_tokens: true
