vocab:
  range:
    numbers: ["", -99, 99]
  misc: [",", ";", "[", "]", "-"]
  special_tokens: {}
  flags:
    include_base_vocab: true
    include_base_special_tokens: true

number_policy:
  attach_sign: true  # true = attach sign to number, false = separate sign as token
  digit_group: 2
  allow_float: true

strict: true
include_base_vocab: true
