vocab:
  range:
    numbers: ["", -9, 9]
  misc: [",", ";", "[", "]", "-", "."]
  special_tokens: {}
  flags:
    include_base_vocab: true
    include_base_special_tokens: true

number_policy:
  separate_sign: false  # false = attach sign to number, true = separate sign as token
  digit_group: 1
  allow_float: true

strict: true
include_base_vocab: true
