dataset:
  save_dir: "./data"
  num_train_samples: 1000
  num_test_samples: 1000
  batch_size: 1000
  n_jobs: 1
  root_seed: 123
  verbose: true
  backend: "sagemath"
  save_text: true
  save_json: false