# Groebner task over ZZ: F=[f1,f2] -> Groebner basis G of (F)

sampler:
  symbols: "x,y"
  field_str: "ZZ"
  order: "degrevlex"
  max_num_terms: 5
  max_degree: 4
  min_degree: 1
  max_coeff: 5
  degree_sampling: "uniform"
  term_sampling: "uniform"

problem_generator:
  num_polynomials: 2

dataset:
  save_dir: "./data/ZZ"
  num_train_samples: 100000
  num_test_samples: 1000
  batch_size: 10000
  n_jobs: 32
  root_seed: 42
  verbose: true
  backend: "sagemath"
  save_text: true
  save_json: false

