dataset:
  save_dir: "./data"
  num_train_samples: 100
  num_test_samples: 20
  batch_size: 10000
  n_jobs: 4
  root_seed: 42
  verbose: true
  backend: "sagemath"
  save_text: false
  save_json: false
