vocab:
  range:
    numbers: ["", -999, 999]
  misc: ["+", "-", "*", "^", "(", ")", "/", ",", "]", "|", "x", "y", "z"]
  special_tokens: {}
  flags:
    include_base_vocab: true
    include_base_special_tokens: true

number_policy:
  attach_sign: true
  digit_group: 3
  allow_float: false

strict: true
include_base_vocab: true
