sampler:
  symbols: "x,y"
  field_str: "GF37"
  order: "lex"
  max_num_terms: 3
  max_degree: 2
  max_coeff: 2
  num_bound: 3

problem_generator:
  min_polynomials: 3
  max_polynomials: 3

dataset:
  save_dir: "./data/GF37"
  num_train_samples: 100000
  num_test_samples: 1000
  batch_size: 10000
  n_jobs: 4
  root_seed: 42
  verbose: true
  backend: "sagemath"
  save_text: true
  save_json: true

