problem_generator:
  field_str: "GF7"
  min_length: 3
  max_length: 6

dataset:
  save_dir: "./data/GF7"
  num_train_samples: 100000
  num_test_samples: 1000
  batch_size: 10000
  n_jobs: 32
  root_seed: 42
  verbose: true
  backend: "sagemath"
  save_text: true
  save_json: true